### ISSUE TITLE
ETABS_Toolkit: Require feature to update the ETABS sections from predefined sections in ETABS.

### ISSUE THREAD

**Issue by nirbhay93** [BHoM/ETABS_Toolkit#233] opened 2019-11-28 11:56 UTC
#### Description:
Require feature to update the ETABS sections from predefined sections in ETABS.
Currently failing to push the updated member done with SetProperty.

Respective script and sample ETABS file in the link below:
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/Issue?csf=1&e=HdaD1B

**Comment by IsakNaslundBh** [comment] 2020-01-07 15:45
@nirbhay93 would you mind clarifying if the problem is:

1. Bars not getting assigned the new section when being updated

or 

2. Sections not getting their value updated to a new one.

**Comment by nirbhay93** [comment] 2020-01-10 05:18
> @nirbhay93 would you mind clarifying if the problem is:

Here, basically I mean to say that both bars and panels are not getting updated with the section properties already predefined in ETABS.

**Comment by IsakNaslundBh** [comment] 2020-03-02 14:54
Think this is a duplicate of https://github.com/BHoM/ETABS_Toolkit/issues/102

**Comment by IsakNaslundBh** [comment] 2020-03-18 16:01
This is closed by the additional PushType `CreateNonExisting`

https://github.com/BHoM/BHoM_Adapter/pull/205

**Closed by IsakNaslundBh** 2020-03-18 16:01 UTC
Labels: type:feature
