### ISSUE TITLE
Etabs Adapter is not able to launch Etabs

### ISSUE THREAD

**Issue by verasluijter** [BHoM/ETABS_Toolkit#420] opened 2023-02-17 14:35 UTC
#### Description:
When using the Etabs adapter and toggling it to active, it doesn't seem to be able to launch Etabs. It does start doing it, showing the etabs start-up frame on my screen. But then it closes off and gives this error:

_1. This component failed to run properly.
- Error: Failed to read from an IPC Port: The pipe has been ended. - Occured in  BH.Adapter.ETABS.ETABSAdapter..ctor(String filePath, EtabsSettings etabsSetting, Boolean active)
     called from BH.UI.Base.Caller.Run(List`1 inputs)
- Are you sure you have the correct type of inputs? Check their description for more details._

When I already have etabs open, it does work. So the problem is in the launching. I have Etabs 19 installed.

#### Steps to reproduce:
Just use the etabs adapter and set it to active.

#### Expected behaviour:
That it can launch etabs.

#### Test file(s):
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/ETABS_Toolkit/Issue%20Etabs%20Adapter%20is%20not%20able%20to%20launch%20Etabs/[Etabs_fail.gh](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/ETABS_Toolkit/Issue%20Etabs%20Adapter%20is%20not%20able%20to%20launch%20Etabs/Etabs_fail.gh?csf=1&web=1&e=vJihll)?csf=1&web=1&e=vJihll

**Comment by alelom** [comment] 2023-02-28 11:41
Thanks @verasluijter, could you confirm:
- which version of ETABS you are using when you experience this bug
- which version of the BHoM installer where you experiencing this on, or if you compiled from source and the specific branch you used

**Comment by verasluijter** [comment] 2023-02-28 12:31
@alelom 
Etabs 19
BHoM v6.1.0.230131

**Comment by alelom** [comment] 2023-02-28 13:09
Thanks @verasluijter , this is because ETABS 19 is not yet supported, as mentioned in the ReadMe:
https://github.com/BHoM/ETABS_Toolkit#readme

I will close this issue as not a bug, but feel free to raise a new "feature" issue requesting the support of ETABS 19.

**Comment by IsakNaslundBh** [comment] 2023-02-28 14:26
Etabs 19 should actually work - readme is out of date.

**Comment by IsakNaslundBh** [comment] 2023-03-17 15:06
Have had a look at this now, and get the same behaviour on my machine.

Updating the nugets have sorted this problem my end, but a bit cautious of making a nuget upgrade this close to beta release.

so either we live with the fact that one has to start Etabs before activating the adapter, or we make the slightly risky Nuget upgrade.. Currently leading to option one for now, even if it means slightly worse UX, as the adapter at least on my end works just fine as long as ETABS is running before it is activated.

**Comment by alelom** [comment] 2023-03-17 17:36
Not sure what the adoption of ETABS_Toolkit is, just wanted to mention that in some cases not doing Nuget updates is also not risk-free, and this seems to be one of such cases. Personally if time permits (if we have resources to test) my choice would be second one, to upgrade packages, test by going through full test procedure, and if other bugs are found they can be tackled in next sprint.

**Closed** 2024-02-14 22:39 UTC
Labels: type:bug
